version: '3'
services:
    mongodb:
        image: mongo
        container_name: pichayon-mongodb
        volumes:
            - ../deployment/pichayon/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - default
    nats-server:
        image: nats
        container_name: pichayon-nats-server
        ports:
            - 4222:4222
        volumes:
            - /etc/localtime:/etc/localtime:ro
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - default
    web:
        build: .
        image: pichayon-image
        container_name: pichayon-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 9000:9000
        links:
            - mongodb
        depends_on:
            - mongodb
        networks:
            - default
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        environment:
            PICHAYON_SETTINGS: /app/pichayon-production.cfg
        command: /venv/bin/gunicorn -w 2 --bind 0.0.0.0:9000 "pichayon.web:create_app()"
    controller:
        build: .
        image: pichayon-image
        container_name: pichayon-controller
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        links:
            - mongodb
            - nats-server
        depends_on:
            - nats-server
            - mongodb
        networks:
            - default
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        environment:
            PICHAYON_SETTINGS: /app/pichayon-production.cfg
        command: /venv/bin/pichayon-controller
networks:
    default:
