version: '3'
services:
    mongodb:
        image: mongo
        container_name: pichayon-mongodb
        volumes:
            - ../deployment/pichayon/mongodb/data/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - default
    web:
        build: .
        image: pichayon-image
        container_name: pichayon-web
        volumes:
            - ../deployment:/deployment
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 8080:9000
        links:
            - mongodb
        depends_on:
            - mongodb
        networks:
            - default
        restart: always
        environment:
            YANA_SETTINGS: /app/pichayon-production.cfg
        command: uwsgi --lazy-apps --ini /app/scripts/pichayon-uwsgi-web.ini
networks:
    default:
