- name: Deploy pichayon door controller 
  hosts: all
  tasks:
    - name: login for internet access
      ansible.builtin.script: /home/surawut/Codes/login/exec_login_aarch64

    - name: Pulling source code from gitlab
      ansible.builtin.git:
        repo: 'https://gitlab.com/r202-coe-psu/pichayon.git'
        dest: /home/pcy/pichayon
        clone: yes
        update: yes

    - name: Installing or updating packages using poetry
      ansible.builtin.shell:
        cmd: "cd /home/pcy/pichayon \
        && ./venv/bin/poetry config virtualenvs.create false \
        && ./venv/bin/poetry install --no-interaction --only main"
        

    - name: Enable service pichayon-door
      become: true
      ansible.builtin.service:
        name: pichayon-door
        enabled: true

    - name: Make sure a service pichayon-door unit is running before restart
      become: true
      ansible.builtin.service:
        state: started
        name: pichayon-door

    - name: Restart service pichayon-door
      become: true
      ansible.builtin.service:
        name: pichayon-door
        state: restarted

    - name: Make sure a service pichayon-door unit is running after restart
      become: true
      ansible.builtin.service:
        state: started
        name: pichayon-door
