# Database Section
MONGODB_DB = "pichayondb"

APP_TITLE = "PICHAYON"

SPARKBIT_ENABLE = False

# message config
PICHAYON_MESSAGE_NATS_HOST = "localhost:4222"
PICHAYON_DOOR_READER = "ASR1200E"
PICHAYON_DOOR_RELAY_ACTIVE_HIGH = True

# ALLOW WEB
PICHAYON_WEB_ALLOW_IPS = []

TINYDB_STORAGE_PATH = "data/db.json"

DEFAULT_KEY_TYPE_A = 'FFFFFFFFFFFF'
DEFAULT_KEY_TYPE_B = 'FFFFFFFFFFFF'