# Database Section
MONGODB_DB = "pichayondb"

APP_TITLE = "PICHAYON"

SPARKBIT_ENABLE = False

# message config
PICHAYON_MESSAGE_NATS_HOST = "localhost:4222"
PICHAYON_DOOR_READER = "ASR1200E"
PICHAYON_DOOR_RELAY_ACTIVE_HIGH = True


TINYDB_STORAGE_PATH = "data/db.json"
